### PR TITLE
Bumped version to 0.2.0, fixed pyt.formatters ModuleNotFoundError issue

### PR DESCRIPTION
**Pull request by KevinHock**
Fixing the issue that @noraj helpfully reported. Also @MacBox7 can you please bump the version in 5 minutes that is on pypi and also, maybe add KevinHock on PyPI as a maintainer of the `python-taint` package.

### CODE REVIEW

**Comment by MacBox7** [comment]
Added you as a maintainer. Would update it tomorrow, going to sleep. Hope it won't be a problem.

**Comment by KevinHock** [comment]
No worries @MacBox7, thanks so much 👍

**Comment by MacBox7** [comment]
I am having trouble in running pyt, getting the following error:
```
Traceback (most recent call last):
  File "/home/ankit/virtualenvironment/pyt/bin/pyt", line 11, in <module>
    sys.exit(main())
  File "/home/ankit/virtualenvironment/pyt/lib/python3.6/site-packages/pyt/__main__.py", line 299, in main
    args.trigger_word_file
  File "/home/ankit/virtualenvironment/pyt/lib/python3.6/site-packages/pyt/vulnerabilities.py", line 520, in find_vulnerabilities
    definitions = parse(vulnerability_files.triggers)
  File "/home/ankit/virtualenvironment/pyt/lib/python3.6/site-packages/pyt/trigger_definitions_parser.py", line 51, in parse
    with open(trigger_word_file, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ankit/virtualenvironment/pyt/lib/python3.6/site-packages/pyt/vulnerability_definitions/flask_trigger_words.pyt'
```

Using `python 3.6.3`
Command: `pyt -f django_XSS.py`

**Comment by MacBox7** [comment]
And one more problem, the current version is `0.2.0` but earlier we have uploaded versions of the scheme like `0.11` and `0.12`. So, as you can see the previous version succeeds the latest version and hence `pip install python-taint` would install `0.12` over `0.2.0`. So, should I delete the previous releases or you would bring a change in the new version naming scheme?

**Comment by KevinHock** [comment]
@MacBox7  I shall fix both of these soon, thank you.

**Pull request merged**
