### PR TITLE
interprocedural_cfg.py: Works for python3.5

### PR DESCRIPTION
**Pull request by MacBox7**

### CODE REVIEW

**Comment by MacBox7** [comment]
I don't understand why it is showing me these issue on change of a single line. All tests pass locally. I think these issues have been ignored before :stuck_out_tongue_closed_eyes:

**Comment by KevinHock** [comment]
I was going to add the tox but it's a bit of a headache having a standard place where everyone's python binaries are https://github.com/python-security/pyt/pull/88/files I guess I'll just look manually in the future, at least there won't be syntax errors due to f-strings in the future.

**Comment by MacBox7** [comment]
@KevinHock since the version is fixed, I guess it would be better to release 0.1 once again. I would even add docs for it afterwards.

**Comment by KevinHock** [comment]
@MacBox7 great point https://github.com/python-security/pyt/releases has been released 👍 I'll add docs in the form of a changelog.md a little later

**Comment by MacBox7** [comment]
Tag me anytime you want a version update 😄

**Pull request merged**
